name: 'Build and Test Workflow'
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, edited]
jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    container: akosfulop/sleeping-barber-builder
    defaults:
      run:
        working-directory: ./build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup build directory
        run: mkdir build
        working-directory: .
      - name: Configure
        run: cmake ..
      - name: Build
        run: cmake --build .
      - name: Run unit tests
        run: ctest --output-on-failure
